CREATE TABLE TipoPessoa (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(10) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE TipoVeiculo (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR(10) NULL,
  PRIMARY KEY(id)
);

CREATE TABLE EstadoCivil (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descricao VARCHAR NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Veiculo (
  placa VARCHAR(8) NOT NULL AUTO_INCREMENT,
  idTipoVeiculo INTEGER UNSIGNED NOT NULL,
  capacidade FLOAT() NULL,
  descricao VARCHAR(64) NULL,
  PRIMARY KEY(placa),
  FOREIGN KEY(idTipoVeiculo)
    REFERENCES TipoVeiculo(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Cliente (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idTipoPessoa INTEGER UNSIGNED NOT NULL,
  nome VARCHAR NULL,
  endereco VARCHAR NULL,
  telefone VARCHAR NULL,
  email VARCHAR NULL,
  inscricaoEstadual VARCHAR NULL,
  datCadastro VARCHAR(8) NULL,
  cpf VARCHAR NULL,
  cnpj VARCHAR NULL,
  rg VARCHAR NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(idTipoPessoa)
    REFERENCES TipoPessoa(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Funcionario (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idEstadoCivil INTEGER UNSIGNED NOT NULL,
  nome VARCHAR NULL,
  endereco VARCHAR NULL,
  telefone VARCHAR NULL,
  email VARCHAR NULL,
  genero CHAR NULL,
  datAdmissao VARCHAR(8) NULL,
  datNasc VARCHAR(8) NULL,
  cpf INTEGER UNSIGNED NULL,
  rg VARCHAR NULL,
  cargo VARCHAR NULL,
  salario FLOAT NULL,
  cnh VARCHAR NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(idEstadoCivil)
    REFERENCES EstadoCivil(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE Usuario (
  idUsuario INTEGER UNSIGNED NOT NULL,
  idCliente INTEGER UNSIGNED NOT NULL,
  idFuncionario INTEGER UNSIGNED NOT NULL,
  nome INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idUsuario),
  FOREIGN KEY(idCliente)
    REFERENCES Cliente(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idFuncionario)
    REFERENCES Funcionario(id)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


